#!/bin/sh
# Copyright (c) 2019 Quamotion bvba
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#
# This is a stub for xcrun. It is used by Appium to list all simulators.
# Because there are no simulators in this Docker container, we can just
# return an empty JSON array.
echo "{}"